name: Laravel

on: [push, pull_request]

jobs:
  laravel-tests:
    environment: production
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_USER: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file from secure vars
      run: |
        touch .env
        echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
    - name: Laravel Setup
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: |
        php artisan migrate
        vendor/phpunit/phpunit/phpunit
